services:
  - docker
script:
  - docker image build -t lawrencefreemankubrick/imagetest .
deploy:
  provider: script
  script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && docker push lawrencefreemankubrick/imagetest
